### ISSUE TITLE
[FEATURE] Social icons to have relevant colour

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/CreatorsRegistry#102]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

All social icons are currently black, it would be good for them to have their relevant colour

### Proposed Solution

color should be in the config file `src/config/app.json`

### Do you want to work on this issue?

No

**Comment by akash19coder** [comment]
i want to work on this issue. could you please assign it to me?

**Comment by eddiejaoude** [comment]
sure i will assign it to you @akash19coder 👍
