### ISSUE TITLE
[BUG] External links are missing target _blank

### ISSUE THREAD

**Issue by Idrinth** [EddieHubCommunity/CreatorsRegistry#107]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Version of CreatorsRegistry (for example "v0.19.0")

0.23.0

### Description

External links currently open in the same window, leading to an unexpected leaving of the site. Affected are at least:

- The github link in the header
- Platform links on the user's profile

### Steps to Reproduce

Github link:
1) Open the website
2) Left-Click the icon
3) See the page not opening in a new tab

Profile links:
1) Go to any profile page
2) Left-Click any platform
3) See the page not opening in a new tab

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

add attributes to the mentioned links:

- target _blank - to open in a new tan
- rel noreferrer - if missing to prevent access from target site javascript

**Comment by eddiejaoude** [comment]
Thanks for raising 👍  I have assigned it to you
