### ISSUE TITLE
[FEATURE] add medium as blog platform

### ISSUE THREAD

**Issue by Idrinth** [EddieHubCommunity/CreatorsRegistry#108]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I am using medium to post blogs and would love to list it.

### Proposed Solution

Add medium to the available platforms

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

- adjust the list of platforms to include medium as a new option
- add medium icon so the profile list can be displayed properly

**Comment by eddiejaoude** [comment]
Thanks for raising the issue 👍  I  have added the Medium icon
