### ISSUE TITLE
[BUG] missing alt on img tags

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [EddieHubCommunity/CreatorsRegistry#112]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production, error is thrown in development mode

### Version of CreatorsRegistry (for example "v0.19.0")

0.24.0

### Description

The `alt` property for Image is set to `description` and many profiles are missing `description` field as a result `alt` field is empty in many cases. Also image `alt` should be set to something descriptive such as `Eddie Jaoude avatar` or something instead of `description`.

![image](https://github.com/EddieHubCommunity/CreatorsRegistry/assets/54144759/92898f21-13c3-4f88-814d-18c49e7ab639)

### Steps to Reproduce

1. Go to Homepage.
2. Inspect profile images using developer tools to find missing alt property

Or

1. Start development server
2. Go to Homepage
3. Open Console in Inspect window and you will see errors related to missing alt property

### Screenshots

![image](https://github.com/EddieHubCommunity/CreatorsRegistry/assets/54144759/f94fa5df-e99c-48c0-950d-308ad3b5cf11)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Instead of `data.description`, set alt to something meaningful for avatars.
Proposed - Name + "avatar" like `Eddie Jaoude avatar`

Any suggestions are welcomed

**Comment by eddiejaoude** [comment]
Than you for raising a great issue 👍  I have assigned it to you
