### ISSUE TITLE
[BUG] Docker image don't use multi stage building

### ISSUE THREAD

**Issue by the-mzakrzewski** [EddieHubCommunity/CreatorsRegistry#120]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Local dev environment

### Version of CreatorsRegistry (for example "v0.19.0")

0.26.1

### Description

Docker image does not use a multi-stage build process. This results in a larger docker image at the end.

### Steps to Reproduce

Just build environment locally.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I would make a PR with stages in Docker image

**Comment by eddiejaoude** [comment]
Thank you @the-mzakrzewski , I have assigned it to you
