### ISSUE TITLE
Missing Application Logo in README

### ISSUE THREAD

**Issue by rajneesh-18** [EddieHubCommunity/CreatorsRegistry#22]
### Description

The README file currently does not include the application's logo. Including the logo at the top of the README can enhance the project's branding and visual appeal, making it more recognizable and professional to visitors and contributors.

### Screenshots

![image](https://github.com/EddieHubCommunity/CreatorsRegistry/assets/112794051/8535dd67-56b5-4625-982a-160cd2d6af28)

### Additional information

Update the README file to include the logo at the top.

**Comment by eddiejaoude** [comment]
Good idea 👍

**Comment by MukarramHaq** [comment]
Can you assign this issue to me?

**Comment by rajneesh-18** [comment]
> Good idea 👍
> 
> File to logo `public/logo.svg`

Exactly Eddie

**Comment by eddiejaoude** [comment]
Sorry, a PR has been raised @MukarramHaq already - we should be assigning first, but I need to update the docs first so people know, I will try to do this soon

@MukarramHaq what about this issue? https://github.com/EddieHubCommunity/CreatorsRegistry/issues/29
