### ISSUE TITLE
[Bug] Prisma Find many

### ISSUE THREAD

**Issue by Jahkamso** [EddieHubCommunity/CreatorsRegistry#27]
### Description

I created, and added the contents in the .env.example file to the .env file, ran npm ci and npm run dev in the terminal, then it threw this error.

### Screenshots

<img width="1638" alt="image" src="https://github.com/EddieHubCommunity/CreatorsRegistry/assets/79403916/41fb8b8e-2a6b-428b-9f0d-ba4c9cfd1fae">

**Comment by eddiejaoude** [comment]
The error is with your local setup, check Postgres is running and the connection string in `.env` is correct.

As this is not a bug with the App, I will close. If you need any help please ask in the EddieHub Discord help channel http://discord.eddiehub.org
