### ISSUE TITLE
Issue templates 

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/CreatorsRegistry#29]
### Description

Copy files from here (all files but not testimonials) https://github.com/EddieHubCommunity/BioDrop/tree/main/.github/ISSUE_TEMPLATE

**Comment by mathanraj0601** [comment]
Like to work on this Eddie can i get assigned?

**Comment by eddiejaoude** [comment]
Sure assigned to you @mathanraj0601

**Comment by mathanraj0601** [comment]
That's Great eddie, Will raise PR asap !
