### ISSUE TITLE
[FEATURE] create local development setup guide

### ISSUE THREAD

**Issue by sital002** [EddieHubCommunity/CreatorsRegistry#36]
### Description

Currently, there is no proper guide on how to setup the project locally.
Adding a proper documentation on how to setup prisma, postrgres and install all necessary dependecies.

**Comment by eddiejaoude** [comment]
We have some information, but more is always helpful 👍 Can you be more specific?

This is what we have already 
<img width="953" alt="Screenshot 2024-06-17 at 19 43 42" src="https://github.com/EddieHubCommunity/CreatorsRegistry/assets/624760/9c86d213-db4e-4a2d-b3b3-cd4ae0b9910d">

**Comment by sital002** [comment]
https://github.com/typehero/typehero/blob/main/LOCAL.md
I think we can have something like this and I noticed the ```.env``` file isn't added in ```.gitignore```

**Comment by eddiejaoude** [comment]
> I noticed the .env file isn't added in .gitignore

good spot 👍

**Comment by eddiejaoude** [comment]
I think this is now complete with Docker and Docker compose and the relevant documentation in the README - I will close this for now but we can create a new one if needed
