### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/CreatorsRegistry#6]
- platform
- reach
- price

**Comment by st17931** [comment]
Pls assign me this task, i have successfully setup the project locally

**Comment by eddiejaoude** [comment]
Hi, sorry @st17931  I am already working on this, and I forgot to assign it to myself. Would you like to work on https://github.com/EddieHubCommunity/CreatorsRegistry/issues/16 , if yes I can assign it to you?

**Comment by st17931** [comment]
yes sure.

**Comment by eddiejaoude** [comment]
@st17931 please comment on the issue and I can then assign it to you
