### ISSUE TITLE
Pop-up warning appears when trying to sign in

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/CreatorsRegistry#77]
### Issue
When I clicked on the Sign in button, a warning message appeared that the form issue not secure. This can cause creators to not want to continue using the site due not wanting their content to be hacked. 

### Screenshots

![Screenshot of issue](https://github.com/EddieHubCommunity/CreatorsRegistry/assets/105683440/b1071810-6694-44a1-9495-1d7a11bc0580)

**Comment by eddiejaoude** [comment]
Thank you for raising 👍  This has now been fixed, I needed to update the redirect url from `http` to `https`
