### ISSUE TITLE
[FEATURE] GitHub link to repo in footer

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/CreatorsRegistry#79]
### Description

So people can easily log issues and star the repo add a GitHub link `https://github.com/EddieHubCommunity/CreatorsRegistry` to the footer

File to update `src/components/Footer.js`

<img width="1266" alt="Screenshot 2024-06-25 at 00 31 03" src="https://github.com/EddieHubCommunity/CreatorsRegistry/assets/624760/32f027fd-2baa-4081-9540-6a1fa26eaceb">

**Comment by devesh-2002** [comment]
May I take up this issue?

**Comment by eddiejaoude** [comment]
Sure @devesh-2002 , I have assigned it to you

**Comment by Shubhdeep02** [comment]
Hey @eddiejaoude can i take this token?

**Comment by eddiejaoude** [comment]
@Shubhdeep02 this issue is already assigned, please select an issue that is ready for dev and not already assigned - you can read more about it in our contributing guide https://github.com/EddieHubCommunity/CreatorsRegistry/blob/main/CONTRIBUTING.md#working-on-an-issue-get-it-assigned-to-you

**Comment by Shubhdeep02** [comment]
thanks @eddiejaoude for guiding . Its so much to learn from your youtube videos.
