### ISSUE TITLE
[FEATURE] add Blog options to the dropdown menu

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/CreatorsRegistry#80]
### Description

I noticed that the Platform section only offers social media accounts to use as a platform link. My Dev.to and Hashnode blogs are the platforms that has brought me the most paid content creation opportunities, so I highly recommend add them as options in the menu[^1]

[^1]: This will also encourage tech bloggers to use the site

### Screenshots

![platform option](https://github.com/EddieHubCommunity/CreatorsRegistry/assets/105683440/a731a95f-b8f1-476d-a527-54d1fa46ae1a)

**Comment by eddiejaoude** [comment]
Yes I am keen to add other platforms, thank you for the suggestions 👍

**Comment by eddiejaoude** [comment]
Unfortunately, those icons are not available in the library we use https://github.com/couetilc/react-social-icons, so we may have to switch libraries

**Comment by eddiejaoude** [comment]
I think FontAwesome has the social logos https://fontawesome.com/search

**Comment by CBID2** [comment]
Here's the icons [for Hashnode](https://fontawesome.com/icons/hashnode?f=brands&s=solid)and [dev.to](https://fontawesome.com/icons/dev?f=brands&s=solid)

**Comment by shivansh84ya** [comment]
Could you please assign this issue to me @eddiejaoude

**Comment by eddiejaoude** [comment]
Icons have been refractored and those blogging platforms have been added

<img width="1301" alt="Screenshot 2024-06-27 at 21 18 53" src="https://github.com/EddieHubCommunity/CreatorsRegistry/assets/624760/43abde77-6d7c-436f-b8cb-e95407e072f5">
