### ISSUE TITLE
[FEATURE] Allow user to update email

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/CreatorsRegistry#82]
### Description

> there should be a way for me to update my email address. I think it gets my email from my LinkedIn login but that is not the one I want to share.

- settings forms show current email from linkedin (not editable)
- settings form to have override email (extra form field)
- on user profile page, use override email if exists

**Comment by lovishduggal** [comment]
Could I work on this issue?

**Comment by eddiejaoude** [comment]
This is already assigned, please check before commenting.

**Comment by eddiejaoude** [comment]
Complete here https://github.com/EddieHubCommunity/CreatorsRegistry/commit/610c8275dcb629793674d8c54021010f606b80bd
