### ISSUE TITLE
[FEATURE]: Add a message when No results found after applying the filter

### ISSUE THREAD

**Issue by RajeevDash007** [EddieHubCommunity/CreatorsRegistry#89]
### Description

A message box needs to be created when no results found after applying filters

### Screenshots

![Screenshot (298)](https://github.com/EddieHubCommunity/CreatorsRegistry/assets/96860040/9b191b4b-3297-451e-8313-06ac2328ef5b)

**Comment by RajeevDash007** [comment]
what type of message you need to add , and what type UI it should be ? 
please let me know.
and if you can provide the particular file name that needs to be edited
and you can assign me this.
@eddiejaoude

**Comment by eddiejaoude** [comment]
Good spot 👍 

We have an `Alert` component that can be used to display the message. Let me know if you would like me to assign it to you

**Comment by RajeevDash007** [comment]
sure @eddiejaoude ,
I will love to add it

**Comment by eddiejaoude** [comment]
ok great, assigned it to you @RajeevDash007
