### ISSUE TITLE
Login Button is visible after you logged in

### ISSUE THREAD

**Issue by Idrinth** [EddieHubCommunity/CreatorsRegistry#91]
### Description

I assume it's a cache issue, but the login option stays in the center of the screen after logging in. This made me think, that I was not logged in at first, before noticing the small profile picture to the top-right.

### Screenshots

![image](https://github.com/EddieHubCommunity/CreatorsRegistry/assets/7874631/a698c54a-dd23-4e1e-9865-968f9bb4e72e)

**Comment by RajeevDash007** [comment]
After reviewing the design, I noticed that the "Sign In" button is already present in the navigation bar. Therefore, it seems redundant to include the same button within this box. I recommend removing the button from the box to streamline the user interface.

**Comment by eddiejaoude** [comment]
The button on the home page is to encourage people who just landed on the app to sign up, we should keep it for now.

This issue is a good idea, as there is no check for the sign in button on the home page

**Comment by eddiejaoude** [comment]
Now the section is hidden if logged in
