### ISSUE TITLE
[FEATURE] Display app version number

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/CreatorsRegistry#93]
### Description

- version number is available in `src/config/app.json`
- display in the footer after the existing text with ` | v0.0.0`

**Comment by RajeevDash007** [comment]
I need some more details on this.
1. what texts do you want to add with the version no.?
2. what should be the placement of that div? left, center or right of the footer

![Content Creators](https://github.com/EddieHubCommunity/CreatorsRegistry/assets/96860040/0006fc12-e6cd-4a2b-80a2-661cac561477)

**Comment by eddiejaoude** [comment]
Great question. I think we can keep it simple for now and just append it to the left. I will update the description

**Comment by RajeevDash007** [comment]
cool!! . got it. Thanks

you can assign me this

I will work on it

**Comment by eddiejaoude** [comment]
Thank you @RajeevDash007 but as this is a "Good First Issue" I am keen to give these type of issues to new people to the project 

How about this issue? https://github.com/EddieHubCommunity/CreatorsRegistry/issues/8

**Comment by RajeevDash007** [comment]
Okay, sure!!
I will look into the issue #8  and will get back to you . Thanks

**Comment by akash19coder** [comment]
I read the conversation history. Since I am just beginning to explore the project it would be a great start for me so please assign this issue to me.

**Comment by eddiejaoude** [comment]
Sure, I have assigned it to you @akash19coder
